### ISSUE TITLE
Fixup license, notice, and code blocks

### ISSUE THREAD

**Issue by 6a68** [mozilla/idea-town-splash#34]
License: the Amazon portions are Apache 2 licensed. I don't know how we mix that with MPL2. I'm fine with this repo being Apache 2 licensed, idk.

Notice: As long as we have a NOTICE file that includes the contents of the original repo's NOTICE file, I think we are fine to remove the existing copyright-related code block from server.js, based on http://www.apache.org/dev/apply-license.html#copy-per-file.

Code blocks: I think @pdehaan has some magic little thing that shoves the MPL code block into the top of files. We could do that, it'd be nice, but not necessary.

**Comment by pdehaan** [comment]
@pdehaan manually copy/pastes MPL headers. He has a Grunt task which enforces headers in files. I can work on rewriting that for Gulp (unless something already exists).

**Comment by meandavejustice** [comment]
https://www.npmjs.com/package/gulp-header

**Comment by 6a68** [comment]
Yeah, this language in the [apache license](http://www.apache.org/licenses/LICENSE-2.0) seems to indicate that a NOTICE is required:

> "Derivative Works" shall mean any work, whether in Source or Object form, that is based on (or derived from) the Work and for which the editorial revisions, annotations, elaborations, or other modifications represent, as a whole, an original work of authorship. For the purposes of this License, Derivative Works shall not include works that remain separable from, or merely link (or bind by name) to the interfaces of, the Work and Derivative Works thereof.

I'll quickly add this.

**Comment by 6a68** [comment]
More background: https://www.mozilla.org/MPL/license-policy.html

**Comment by 6a68** [comment]
And, per [the flowchart](https://www.mozilla.org/MPL/license-policy-flowchart.png), we'll license our repo as Apache 2, since we're working from a project with that license
