### ISSUE TITLE
If server returns a statusCode:400, user still gets a "thank you" message when signing up to waitlist

### ISSUE THREAD

**Issue by pdehaan** [mozilla/idea-town-splash#90]
Ref: https://github.com/mozilla/idea-town/pull/75#discussion_r36571105

```sh
$ git log -1 --oneline # 56bd040 Merge pull request #83 from mozilla/issue-70
```

### Steps to reproduce:
1. Set up idea-town locally (but don't configure EBS or AWS creds).
2. Sign up to the waitlist (you can use "foo@localhost").
3. Click the "Sign up" button to register for the waiting list.
4. View the Terminal console output.

### Actual results:
Since I don't have a backend set up, I'd expect a hard fail. But the front end shows a happy path while the server cries on the floor.

![idea_town](https://cloud.githubusercontent.com/assets/557895/9210133/4fa2e3ec-402f-11e5-9cab-4abbe034e874.png)

![1__node_server__node__and_issues_ _mozilla_idea-town_and_idea_town](https://cloud.githubusercontent.com/assets/557895/9210141/5afa5b94-402f-11e5-9ff9-0ac5593d9016.png)

```
Error adding item to database:  { [ResourceNotFoundException: Requested resource not found]
  message: 'Requested resource not found',
  code: 'ResourceNotFoundException',
  time: Tue Aug 11 2015 13:45:48 GMT-0700 (PDT),
  statusCode: 400,
  retryable: false,
  retryDelay: 0 }
```

**Comment by 6a68** [comment]
Pulling into milestone 1, since we've got an open PR to fix this bug, and it's worth fixing
